import re


def normalize_sql(sql):
    """Normalize SQL for comparison - lowercase, remove extra spaces."""
    if not sql:
        return ""
    sql = sql.lower().strip()
    sql = re.sub(r'\s+', ' ', sql)  # Replace multiple spaces with single space
    sql = re.sub(r'[;]', '', sql)  # Remove semicolons
    return sql


def calculate_sql_match_percent(generated_sql, expected_sql):
    """
    Calculate what percentage of SQL query matches.
    
    Args:
        generated_sql: SQL query generated by the model
        expected_sql: Expected SQL query from test data
        
    Returns:
        Percentage match (0-100)
    """
    if not generated_sql or not expected_sql:
        return 0.0
    
    gen_normalized = normalize_sql(generated_sql)
    exp_normalized = normalize_sql(expected_sql)
    
    # Tokenize SQL
    gen_tokens = set(gen_normalized.split())
    exp_tokens = set(exp_normalized.split())
    
    if not exp_tokens:
        return 0.0
    
    # Calculate intersection
    common_tokens = gen_tokens.intersection(exp_tokens)
    match_percent = (len(common_tokens) / len(exp_tokens)) * 100.0
    
    return round(match_percent, 2)


def normalize_row_values(row):
    """Extract row values as sorted tuple (ignore column names)."""
    values = list(row.values()) if isinstance(row, dict) else list(row)
    return tuple(sorted(values, key=str))


def calculate_answer_match_percent(actual_result, expected_result):
    """Calculate percentage of matching rows."""
    if isinstance(actual_result, str) or not expected_result:
        return 0.0
    
    actual = list(actual_result) if not isinstance(actual_result, list) else actual_result
    expected = list(expected_result) if not isinstance(expected_result, list) else expected_result
    
    if len(expected) == 0:
        return 100.0 if len(actual) == 0 else 0.0
    
    actual_normalized = [normalize_row_values(row) for row in actual]
    expected_normalized = [normalize_row_values(row) for row in expected]
    
    matches = sum(1 for row in expected_normalized if row in actual_normalized)
    return round((matches / len(expected)) * 100.0, 2)


def evaluate_answer(actual_result, generated_sql=None, expected_sql=None, expected_result=None):
    """
    Evaluate SQL and answer accuracy.
    
    Args:
        actual_result: Result from executing SQL (list of dicts or error string)
        generated_sql: SQL query generated by the model
        expected_sql: Expected SQL query from test data
        expected_result: Expected result from test data
        
    Returns:
        Dictionary with: {'syntax_ok': bool, 'sql_match_percent': float, 'answer_match_percent': float}
    """
    # 0. Check for syntax errors first
    # SQL executed successfully if result is not an error string
    syntax_ok = not isinstance(actual_result, str)
    
    # 1. SQL syntax/match percentage
    sql_match_percent = 0.0
    if generated_sql and expected_sql:
        sql_match_percent = calculate_sql_match_percent(generated_sql, expected_sql)
    
    # 2. Answer match percentage
    answer_match_percent = 0.0
    if expected_result:
        answer_match_percent = calculate_answer_match_percent(actual_result, expected_result)
    
    return {
        'syntax_ok': syntax_ok,
        'sql_match_percent': sql_match_percent,
        'answer_match_percent': answer_match_percent
    }
